@echo off
echo Starting MGNREGA Dashboard...
echo.
echo Starting Backend Server...
start "Backend" cmd /k "cd backend && npm run dev"
timeout /t 3 /nobreak > nul
echo Starting Frontend...
start "Frontend" cmd /k "npm run dev"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5001
echo Frontend: http://localhost:5173
pause